#!/bin/sh

cat << EOF > config.sql
FLUSH PRIVILEGES;
CREATE DATABASE IF NOT EXISTS $MARIADB_NM;
CREATE USER IF NOT EXISTS '$MARIADB_USER'@'%' IDENTIFIED BY '$MARIADB_PWD';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '$MARIADB_ROOT_PWD';
GRANT ALL PRIVILEGES ON $MARIADB_NM.* TO '$MARIADB_USER'@'%' WITH GRANT OPTION;
CREATE USER IF NOT EXISTS '$MARIADB_USER'@'localhost' IDENTIFIED BY '$MARIADB_PWD';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '$MARIADB_ROOT_PWD';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY '$MARIADB_ROOT_PWD';
GRANT ALL PRIVILEGES ON $MARIADB_NM.* TO '$MARIADB_USER'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON $MARIADB_NM.* TO '$MARIADB_USER'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
EOF

mysqld --bootstrap < config.sql

chown -R mysql:mysql /run/mysqld /var/lib/mysql

mysqld --user=mysql --datadir=/var/lib/mysql